\ Tests.fs   gforth Tests.fs
INCLUDE ffl/tst.fs
INCLUDE Rent.fs

: TEST-NEXT-EVENT-ID
    EVENT-ID OFF
    T{ NEXT-ID 0 ?S }T 
    T{ NEXT-ID 1 ?S }T ;

: TEST-EVENT-KEY [ HEX ]
    EVENT-ID OFF
    CASH% 12C7 EVENT-KEY T{ 12C70000 ?S }T 
    RENT% 12C7 EVENT-KEY T{ 12C78001 ?S }T [ DECIMAL ] ;

: TEST-RENT-EVENT [ HEX ]
    EVENT-ID OFF 12C7 10 64 RENT-EVENT
    T{ 12C78000 ?S 12D7000064 ?S }T [ DECIMAL ] ;

: TEST-CASH-EVENT [ HEX ]
    EVENT-ID OFF 12C7 CASH-EVENT
    T{ 12C70000 ?S 0 ?S }T [ DECIMAL ] ;

: TEST-ADD-ORDER
    INITIALIZE
    0 5 10 ADD-ORDER
    EVENTS ACT-LENGTH@ T{ 2 ?S }T ;

: TEST-RENT
    INITIALIZE
    0 5 10 RENT
    5 GET-VALUE T{ 10 ?S }T ;

: TEST-CASH
    INITIALIZE
    0 5 10 RENT
    5 CASH
    T{ RENT-VALUE @ 10 ?S }T ;

: TEST-EVENT
    INITIALIZE
    0 5 10 RENT% EVENT
    5 CASH% EVENT
    T{ RENT-VALUE @ 10 ?S }T ;

: TEST-GET-EVENT
    4807 10 100 RENT-EVENT GET-EVENT
    T{ RENT% ?S 100 ?S 4817 ?S 4807 ?S }T
    4807 CASH-EVENT GET-EVENT
    T{ CASH% ?S 4807 ?S }T ;
    

: TEST-COMPUTE-VALUE
    INITIALIZE
    0 5 10 ADD-ORDER
    3 7 14 ADD-ORDER
    5 9  8 ADD-ORDER
    6 9  7 ADD-ORDER
    T{ COMPUTE-VALUE RENT-VALUE @ 18 ?S }T ;
    
PAGE
TEST-NEXT-EVENT-ID
TEST-EVENT-KEY
TEST-RENT-EVENT
TEST-CASH-EVENT
TEST-ADD-ORDER
TEST-RENT
TEST-CASH
TEST-EVENT
TEST-GET-EVENT
TEST-COMPUTE-VALUE
BYE

