\ Tests.fs

INCLUDE ffl/tst.fs
INCLUDE ffl/hct.fs
INCLUDE Rent.fs

: TEST-INITIALIZE
    INIT-RENT
    T{ RENT-VALUE @ 0 ?S }T 
    T{ RENT-VALUES HCT-LENGTH@ 0 ?S }T
    42 S" FOO" RENT-VALUES HCT-INSERT
    INIT-RENT
    T{ RENT-VALUES HCT-LENGTH@ 0 ?S }T
;

: TEST-RENT
    INIT-RENT
    0 5 10 RENT
    T{ 5 RENT-VALUE#@ 10 ?S }T 
;
 
: TEST-ONE-ORDER
    INIT-RENT
    0 5 10 RENT
    5 CASH
    T{ RENT-VALUE @ 10 ?S }T 
;

: TEST-TWO-COLLIDING-ORDERS
    INIT-RENT
    0 5 14 RENT
    3 7 10 RENT
    5  CASH
    10 CASH
    T{ RENT-VALUE @ 14 ?S }T
;
: TEST-TWO-COMPATIBLE-ORDERS
    INIT-RENT
    0 5 10 RENT
    5 CASH
    6 9 7  RENT
    14 CASH
    T{ RENT-VALUE @ 17 ?S }T
;
: TEST-DEMO-CASE
    INIT-RENT
    0 5 10 RENT
    3 7 14 RENT
    5  CASH
    5 9  7 RENT
    6 9  8 RENT
    10 CASH
    14 CASH
    15 CASH
    T{ RENT-VALUE @ 18 ?S }T
;
: TEST-ORDER>EVENTS
    0 5 10 ORDER>EVENTS
    T{ $280000000000 ?S $040000A0000A ?S }T
;

: TEST-DECODE-RENT-EVENT
    $040000A0000A DECODE-EVENT 
    T{ ['] RENT ?S  10 ?S 5 ?S 0 ?S }T 
;
: TEST-DECODE-CASH-EVENT
    $028000000000 DECODE-EVENT
    T{ ['] CASH ?S  0 ?S }T 
;
: TEST-ADD-ORDER
    INIT-RENT
    0 5 10 ADD-ORDER
    RENT-EVENTS ACT-LENGTH@ 
    T{ 2 ?S }T 
;
: TEST-COMPUTE-VALUE
    INIT-RENT
    0 5 10 ADD-ORDER
    3 7 14 ADD-ORDER
    .EVENTS
    COMPUTE-VALUE
    T{ 14 ?S }T ;

TEST-INITIALIZE
TEST-RENT
TEST-ONE-ORDER
TEST-TWO-COLLIDING-ORDERS
TEST-TWO-COMPATIBLE-ORDERS
TEST-DEMO-CASE
TEST-ORDER>EVENTS
TEST-DECODE-RENT-EVENT 
TEST-DECODE-CASH-EVENT 
TEST-ADD-ORDER
TEST-COMPUTE-VALUE

BYE

